/*----------------------------------------------------------------------------*/
/* Copyright (c) 2017-2018 FIRST. All Rights Reserved.                        */
/* Open Source Software - may be modified and shared by FRC teams. The code   */
/* must be accompanied by the FIRST BSD license file in the root directory of */
/* the project.                                                               */
/*----------------------------------------------------------------------------*/

package org.usfirst.frc.team5920.robot;

import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;
import edu.wpi.first.wpilibj.drive.DifferentialDrive;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	// For example to map the left and right motors, you could define the
	// following variables to use with your drivetrain subsystem.
	// public static int leftMotor = 1;
	// public static int rightMotor = 2;

	// If you are using multiple modules, make sure to define both the port
	// number and the module. For example you with a rangefinder:
	// public static int rangefinderPort = 1;
	// public static int rangefinderModule = 1;
	
	public static final int
		driveLeft = 0,
		driveRight = 1;
	public static SpeedController leftDrive;
    public static SpeedController rightDrive;
    public static DifferentialDrive MainDrive;
}

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        leftDrive = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 1", (VictorSP) leftDrive);
        leftDrive.setInverted(false);
        rightDrive = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "Speed Controller 2", (VictorSP) rightDrive);
        rightDrive.setInverted(false);
        MainDrive = new DifferentialDrive(leftDrive, rightDrive);
        LiveWindow.addActuator("DriveTrain", "Differential Drive 1", MainDrive);
        MainDrive.setSafetyEnabled(true);
        MainDrive.setExpiration(0.1);
        MainDrive.setMaxOutput(1.0);
    }

/*
Source / Reference files
NavX
https://www.pdocs.kauailabs.com/navx-mxp/software/roborio-libraries/java/

Talon SRX
https://github.com/CrossTheRoadElec/Phoenix-Documentation/blob/master/README.md

Anything else we are adding this year???


*/